version: "3.8"

services:
  web: # type of a service
    build:
      context: . # files
    ports:
      - 8000:5000
    volumes:
      - ./:/app

  mysqldb:
    image: mysql
    ports:
      - 32000:33060
    environment:
      - MYSQL_ROOT_PASSWORD=duke2030
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql


volumes:
  mysql:
  mysql_config: